# Generated by Django 2.2.6 on 2019-10-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_price', models.PositiveIntegerField(default=0)),
                ('number_of_rooms', models.PositiveIntegerField(default=1)),
                ('apartment_floor', models.PositiveIntegerField(default=1)),
                ('year_of_construction', models.PositiveIntegerField(default=2019)),
                ('apartment_adress', models.CharField(max_length=200)),
            ],
        ),
    ]
