# Generated by Django 2.2.6 on 2019-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='building_floors',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
